const SUPABASE_URL="https://fdgixlbgrbrctwwelnep.supabase.co";
// This is the public/publishable key you provided. Never put a service_role/secret key here.
const SUPABASE_KEY="sb_publishable_FGM2ywOHylJXkrGO6j__6A_sIeMTQH4";
const supabaseClient=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
let authMode="login",readerRecognition=null,readerRunning=false,selectedEmotion=null,challengeRecognition=null,challengeRunning=false,challengeSpoken=false,silenceTimer=null,mediaStream=null;
const $=id=>document.getElementById(id);

document.addEventListener("DOMContentLoaded",async()=>{setupNavigation();setupAuth();setupButtons();const {data}=await supabaseClient.auth.getSession();if(data.session)await enterApp();});
function setupNavigation(){document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>showSection(b.dataset.section,b));document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>showSection(b.dataset.go));$("logout").onclick=logout;}
function showSection(id,btn){document.querySelectorAll(".section").forEach(s=>s.classList.remove("active"));$(id)?.classList.add("active");document.querySelectorAll(".nav").forEach(n=>n.classList.remove("active"));if(btn)btn.classList.add("active");window.scrollTo(0,0)}
function setupAuth(){ $("loginTab").onclick=()=>setAuthMode("login");$("signupTab").onclick=()=>setAuthMode("signup");$("switchBtn").onclick=()=>setAuthMode("signup");setAuthMode("login");supabaseClient.auth.onAuthStateChange((event,session)=>{if(session)enterApp()});}
function setAuthMode(mode){authMode=mode;$("loginTab").classList.toggle("active",mode==="login");$("signupTab").classList.toggle("active",mode==="signup");clearMessage();$("authForm").innerHTML=mode==="login"?`<label>Email</label><input id="email" type="email" autocomplete="email" placeholder="you@example.com"><label>Password</label><input id="password" type="password" autocomplete="current-password" placeholder="Password"><button id="authSubmit" class="primary" style="width:100%;margin-top:20px">Log In</button>`:`<label>Name</label><input id="name" placeholder="Your name" autocomplete="name"><label>Email</label><input id="email" type="email" autocomplete="email" placeholder="you@example.com"><label>Password</label><input id="password" type="password" autocomplete="new-password" placeholder="Create a password"><button id="authSubmit" class="primary" style="width:100%;margin-top:20px">Create Account</button>`;$("authSubmit").onclick=handleAuth;$("switchText").textContent=mode==="login"?"Don't have an account?":"Already have an account?";$("switchBtn").textContent=mode==="login"?"Sign up":"Log in";$("switchBtn").onclick=()=>setAuthMode(mode==="login"?"signup":"login");}
function showMessage(text){$("authMessage").textContent=text;$("authMessage").classList.add("show")};function clearMessage(){$("authMessage").textContent="";$("authMessage").classList.remove("show")}
async function handleAuth(){const email=$("email")?.value.trim(),password=$("password")?.value,name=$("name")?.value.trim();if(!email||!password)return showMessage("Please enter your email and password.");if(authMode==="signup"){if(!name)return showMessage("Please enter your name.");const redirect=window.location.href;const {data,error}=await supabaseClient.auth.signUp({email,password,options:{data:{name},emailRedirectTo:redirect}});if(error)return showMessage(error.message);if(data.session)enterApp();else showMessage("Account created! Check your email to confirm your account, then return to SceneMate.");}else{const {data,error}=await supabaseClient.auth.signInWithPassword({email,password});if(error)return showMessage(error.message);if(data.session)enterApp();}}
async function enterApp(){$("loginPage").classList.add("hidden");$("app").classList.remove("hidden");showSection("home",document.querySelector('.nav[data-section="home"]'));await loadProfile();}
async function logout(){stopReader();stopChallenge(false);await supabaseClient.auth.signOut();$("app").classList.add("hidden");$("loginPage").classList.remove("hidden");setAuthMode("login");}
async function currentUser(){const {data}=await supabaseClient.auth.getUser();return data.user}
async function loadProfile(){const u=await currentUser();if(!u)return;const {data}=await supabaseClient.from("profiles").select("id,name,bio,profile_picture_url,acting_experience").eq("id",u.id).maybeSingle();if(data){$("profileName").value=data.name||u.user_metadata?.name||"";$("profileBio").value=data.bio||"";$("profileExperience").value=data.acting_experience||"";if(data.profile_picture_url)setPhoto(data.profile_picture_url);else initialPhoto(data.name||u.user_metadata?.name||"")}else initialPhoto(u.user_metadata?.name||"");}
async function saveProfile(){const u=await currentUser();if(!u)return;const name=$("profileName").value.trim();if(!name){$("profileStatus").textContent="Please enter your name.";$("profileStatus").classList.add("show");return}const {error}=await supabaseClient.from("profiles").upsert({id:u.id,name,bio:$("profileBio").value.trim(),acting_experience:$("profileExperience").value.trim(),updated_at:new Date().toISOString()},{onConflict:"id"});$("profileStatus").textContent=error?error.message:"✓ Profile saved.";$("profileStatus").classList.add("show");}
function initialPhoto(name){$("profilePhoto").style.display="none";$("profileInitial").style.display="grid";$("profileInitial").textContent=name?name[0].toUpperCase():"🎭"}function setPhoto(url){$("profilePhoto").src=url;$("profilePhoto").style.display="block";$("profileInitial").style.display="none"}
function setupButtons(){$("saveProfile").onclick=saveProfile;$('uploadBtn').onclick=()=>$("photoFile").click();$('photoFile').onchange=e=>{if(e.target.files[0])uploadPhoto(e.target.files[0])};$('cameraBtn').onclick=openCamera;$('analyze').onclick=analyzeScene;$('clearScene').onclick=()=>{$('scriptInput').value="";$('characters').textContent="Analyze your scene to find characters.";$('playerCharacter').innerHTML='<option>Select a character</option>'};$('readerStart').onclick=startReader;$('readerStop').onclick=stopReader;document.querySelectorAll('.emotion').forEach(b=>b.onclick=()=>selectEmotion(b,b.dataset.emotion));$('challengeStart').onclick=startChallenge;$('challengeStop').onclick=()=>stopChallenge(true)}
async function uploadPhoto(file){const u=await currentUser();if(!u)return;$("photoStatus").textContent="Uploading...";const ext=file.type.includes("png")?"png":"jpg",path=`${u.id}/profile.${ext}`;const {error}=await supabaseClient.storage.from("profile-pictures").upload(path,file,{upsert:true,contentType:file.type||"image/jpeg"});if(error){$("photoStatus").textContent="Upload failed: "+error.message;return}const {data}=supabaseClient.storage.from("profile-pictures").getPublicUrl(path);const {error:pe}=await supabaseClient.from("profiles").upsert({id:u.id,profile_picture_url:data.publicUrl,updated_at:new Date().toISOString()},{onConflict:"id"});if(pe){$("photoStatus").textContent="Picture uploaded, but profile update failed.";return}setPhoto(data.publicUrl+"?v="+Date.now());$("photoStatus").textContent="✓ Profile picture saved."}
function openCamera(){if(!navigator.mediaDevices?.getUserMedia)return alert("Camera access is not available in this browser.");navigator.mediaDevices.getUserMedia({video:true,audio:false}).then(stream=>{mediaStream=stream;const modal=document.createElement("div");modal.className="camera-modal";modal.innerHTML='<div class="camera-box"><h2>Take Profile Picture</h2><video id="cameraVideo" autoplay playsinline></video><button id="take" class="primary">Take Picture</button><button id="cancel" class="secondary">Cancel</button></div>';document.body.appendChild(modal);$('cameraVideo').srcObject=stream;$('cancel').onclick=()=>closeCamera(modal);$('take').onclick=()=>{const v=$('cameraVideo'),c=document.createElement('canvas');c.width=v.videoWidth||640;c.height=v.videoHeight||640;c.getContext('2d').drawImage(v,0,0,c.width,c.height);c.toBlob(blob=>{closeCamera(modal);if(blob)uploadPhoto(new File([blob],`profile-${Date.now()}.jpg`,{type:'image/jpeg'}));},'image/jpeg',.9)}}).catch(()=>alert("Camera permission was not granted."))}
function closeCamera(modal){mediaStream?.getTracks().forEach(t=>t.stop());mediaStream=null;modal.remove()}
function analyzeScene(){const text=$("scriptInput").value.trim();if(!text)return $("characters").textContent="Paste your sides first.";const chars=[];text.split(/\r?\n/).forEach(l=>{const n=l.trim();if(/^[A-Z][A-Z0-9 _'-]{1,30}$/.test(n)&&!chars.includes(n))chars.push(n)});if(!chars.length){$("characters").textContent="No character names found. Put character names on their own lines in ALL CAPS.";return}$("characters").innerHTML=chars.map(c=>`<span>${c}</span>`).join(' ');$('playerCharacter').innerHTML='<option>Select a character</option>'+chars.map(c=>`<option>${c}</option>`).join('')}
function startReader(){const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R)return $("readerStatus").textContent="Speech recognition is not available in this browser.";if($("playerCharacter").value==="Select a character")return $("readerStatus").textContent="Choose your character first.";readerRunning=true;readerRecognition=new R();readerRecognition.continuous=true;readerRecognition.interimResults=true;readerRecognition.lang="en-US";readerRecognition.onresult=()=>$("readerStatus").textContent="🎙️ Listening...";readerRecognition.onend=()=>{if(readerRunning)try{readerRecognition.start()}catch(e){}};readerRecognition.onerror=()=>{};try{readerRecognition.start();$("readerStatus").textContent="🎙️ Listening for your lines..."}catch(e){$("readerStatus").textContent="Could not start the microphone."}}
function stopReader(){readerRunning=false;try{readerRecognition?.stop()}catch(e){}readerRecognition=null;$("readerStatus").textContent="AI Reader stopped."}
function selectEmotion(btn,emotion){stopChallenge(false);document.querySelectorAll('.emotion').forEach(x=>x.classList.remove('selected'));btn.classList.add('selected');selectedEmotion=emotion;$('challengeStatus').innerHTML=`✓ ${emotion} selected. Press Start Challenge!`}
async function startChallenge(){const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!selectedEmotion)return $('challengeStatus').textContent="🎭 Choose an emotion first.";if(!R)return $('challengeStatus').textContent="Speech recognition is not available in this browser.";try{mediaStream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}})}catch(e){return $('challengeStatus').textContent="⚠️ Please allow microphone access."}challengeRunning=true;challengeSpoken=false;challengeRecognition=new R();challengeRecognition.continuous=true;challengeRecognition.interimResults=true;challengeRecognition.lang="en-US";challengeRecognition.onresult=e=>{let t="";for(const r of e.results)t+=r[0].transcript+" ";if(t.trim()){challengeSpoken=true;$('challengeStatus').innerHTML=`🎙️ Listening...`;clearTimeout(silenceTimer);silenceTimer=setTimeout(finishChallenge,1400)}};challengeRecognition.onend=()=>{if(challengeRunning)try{challengeRecognition.start()}catch(e){}};challengeRecognition.onerror=()=>{};try{challengeRecognition.start();$('challengeStatus').innerHTML=`🎙️ Go! Perform it as <strong>${selectedEmotion}</strong>.`}catch(e){}}
function finishChallenge(){if(!challengeRunning||!challengeSpoken)return;challengeRunning=false;clearTimeout(silenceTimer);try{challengeRecognition?.stop()}catch(e){}mediaStream?.getTracks().forEach(t=>t.stop());mediaStream=null;$('challengeStatus').innerHTML='🎉 <strong>Good job!</strong>'}
function stopChallenge(show=true){challengeRunning=false;challengeSpoken=false;clearTimeout(silenceTimer);try{challengeRecognition?.abort()}catch(e){}challengeRecognition=null;mediaStream?.getTracks().forEach(t=>t.stop());mediaStream=null;if(show)$('challengeStatus').textContent="⏹️ Challenge stopped."}
